name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: aditya-1123
          outputs: dist/snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
